#!/usr/bin/env python
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

name: hyperreel
channels:
  - pyg
  - pytorch
  - pytorch3d
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - cudatoolkit=11.6
  - cudatoolkit-dev
  - kornia
  - matplotlib
  - pillow
  - python=3.8
  - pip
  - pytorch3d
  - setuptools=59.5.0
  - pytorch=1.12.1
  - pytorch-lightning=1.7.6
  - scikit-image
  - scipy
  - torchvision
  - pip:
    - dearpygui
    - hydra-core==1.1.1
    - imageio
    - iopath==0.1.9
    - lpips==0.1.4
    - omegaconf==2.1.1
    - opencv-python
    - plyfile
    - gdown
